server:
  port: 9080

# for Camel version 2.18 and below
integration:
  api:
    path: '/integration' 

camel:
  springboot:
    # The Camel context name
    name: ServicesRest

# Binding health checks to a different port
management:
  server:
    port: 9081
  endpoints:
    enabled-by-default: false

