server:
  port: 9080

# for Camel version 2.18 and below
integration:
  api:
    path: '/integration' 

camel:
  springboot:
    # Camel context name
    name: ServicesRest

# Binding health to a different port
management:
  server:
    port: 9081
  endpoints:
    enabled-by-default: false

app:
  mappings:
    Thing:
      table: Thing_table
      attr1: column_1
      attr2: column_2
      attr3: column_3
    Another:
      table: AnotherTable
      a1: col1
      a2: col2
